#!/bin/bash
CORE_DIRECTORY=/opt/azerothcore

MYSQL_HOST=10.0.0.100
MYSQL_PORT=3306
MYSQL_USER=acore
MYSQL_PASS=acore
MYSQL_DATA_AUTH=acore_auth
MYSQL_DATA_CHARACTERS=acore_characters
MYSQL_DATA_WORLD=acore_world

WORLD_NAME="Aurora"
WORLD_MOTD="Welcome to Aurora. This is hosted for those who are truly excellent!"
WORLD_ID=1
WORLD_IP=10.0.0.111
WORLD_GAMETYPE=1
WORLD_REALMZONE=8
WORLD_PLAYERLIMIT=1000
WORLD_SKIPCINEMATICS=2
WORLD_STARTLEVEL=1
WORLD_STARTMONEY=0
WORLD_ALWAYSMAXSKILL=0
WORLD_ALLFLIGHTPATHS=0
WORLD_MAPSEXPLORED=0
WORLD_ALLOWCOMMANDS=0
WORLD_QUESTIGNORERAID=1
WORLD_PREVENTAFKLOGOUT=0

WORLD_RATE_MONEY=3
WORLD_RATE_EXPERIENCE=1
WORLD_RATE_REPUTATION=1
WORLD_RATE_CRAFTING=3
WORLD_RATE_DEFENSE=3
WORLD_RATE_GATHERING=3
WORLD_RATE_WEAPON=3
WORLD_RATE_RESTEXP=3

WORLD_GM_LOGINSTATE=1
WORLD_GM_VISIBLE=0
WORLD_GM_CHAT=0
WORLD_GM_WHISPER=0
WORLD_GM_LIST=0
WORLD_GM_WHO=0
WORLD_GM_ALLOWINVITE=0
WORLD_GM_LOWERSECURITY=0

MODULE_AHBOT_ENABLED=true
MODULE_AHBOT_SELLER=1
MODULE_AHBOT_BUYER=1
MODULE_AHBOT_ACCOUNT=1
MODULE_AHBOT_GUID=1
MODULE_AHBOT_MINITEMS=5000
MODULE_AHBOT_MAXITEMS=10000
MODULE_SKIPDKAREA_ENABLED=false
MODULE_KICKSTARTER_ENABLED=true
MODULE_KICKSTARTER_EQUIPMENT=0
MODULE_KICKSTARTER_GEMS=1
MODULE_KICKSTARTER_GLYPHS=1
MODULE_KICKSTARTER_SPELLS=0
MODULE_KICKSTARTER_PROFICIENCY=0
MODULE_KICKSTARTER_PROFICIENCY_MAX=0
MODULE_KICKSTARTER_MOUNTS=0
MODULE_KICKSTARTER_UTILITIES=1
MODULE_KICKSTARTER_UTILITIES_NAME=1
MODULE_KICKSTARTER_UTILITIES_RACE=1
MODULE_KICKSTARTER_UTILITIES_FACTION=1
MODULE_KICKSTARTER_UTILITIES_APPEARANCE=1
MODULE_EXPERIENCED_ENABLED=true

if [[ -z $CORE_DIRECTORY ]] || [[ -z $MYSQL_HOST ]] || [[ -z $MYSQL_PORT ]] || [[ -z $MYSQL_USER ]] || [[ -z $MYSQL_PASS ]] || 
   [[ -z $MYSQL_DATA_AUTH ]] || [[ -z $MYSQL_DATA_CHARACTERS ]] || [[ -z $MYSQL_DATA_WORLD ]] || [[ -z $WORLD_NAME ]] || [[ -z $WORLD_MOTD ]] || 
   [[ -z $WORLD_ID ]] || [[ -z $WORLD_IP ]] || [[ -z $WORLD_GAMETYPE ]] || [[ -z $WORLD_REALMZONE ]] || [[ -z $WORLD_PLAYERLIMIT ]] || 
   [[ -z $WORLD_SKIPCINEMATICS ]] || [[ -z $WORLD_STARTLEVEL ]] || [[ -z $WORLD_STARTMONEY ]] || [[ -z $WORLD_ALWAYSMAXSKILL ]] || [[ -z $WORLD_ALLFLIGHTPATHS ]] || 
   [[ -z $WORLD_MAPSEXPLORED ]] || [[ -z $WORLD_ALLOWCOMMANDS ]] || [[ -z $WORLD_QUESTIGNORERAID ]] || [[ -z $WORLD_PREVENTAFKLOGOUT ]] || [[ -z $WORLD_RATE_MONEY ]] || 
   [[ -z $WORLD_RATE_EXPERIENCE ]] || [[ -z $WORLD_RATE_REPUTATION ]] || [[ -z $WORLD_RATE_CRAFTING ]] || [[ -z $WORLD_RATE_DEFENSE ]] || [[ -z $WORLD_RATE_GATHERING ]] || 
   [[ -z $WORLD_RATE_WEAPON ]] || [[ -z $WORLD_RATE_RESTEXP ]] || [[ -z $WORLD_GM_LOGINSTATE ]] || [[ -z $WORLD_GM_VISIBLE ]] || [[ -z $WORLD_GM_CHAT ]] || 
   [[ -z $WORLD_GM_WHISPER ]] || [[ -z $WORLD_GM_LIST ]] || [[ -z $WORLD_GM_WHO ]] || [[ -z $WORLD_GM_ALLOWINVITE ]] || [[ -z $WORLD_GM_LOWERSECURITY ]] || 
   [[ -z $MODULE_AHBOT_ENABLED ]] || [[ -z $MODULE_AHBOT_SELLER ]] || [[ -z $MODULE_AHBOT_BUYER ]] || [[ -z $MODULE_AHBOT_ACCOUNT ]] || [[ -z $MODULE_AHBOT_GUID ]] || 
   [[ -z $MODULE_AHBOT_MINITEMS ]] || [[ -z $MODULE_AHBOT_MAXITEMS ]] || [[ -z $MODULE_SKIPDKAREA_ENABLED ]] || [[ -z $MODULE_KICKSTARTER_ENABLED ]] || [[ -z $MODULE_KICKSTARTER_EQUIPMENT ]] || 
   [[ -z $MODULE_KICKSTARTER_GEMS ]] || [[ -z $MODULE_KICKSTARTER_GLYPHS ]] || [[ -z $MODULE_KICKSTARTER_SPELLS ]] || [[ -z $MODULE_KICKSTARTER_PROFICIENCY ]] || [[ -z $MODULE_KICKSTARTER_PROFICIENCY_MAX ]] || 
   [[ -z $MODULE_KICKSTARTER_MOUNTS ]] || [[ -z $MODULE_KICKSTARTER_UTILITIES ]] || [[ -z $MODULE_KICKSTARTER_UTILITIES_NAME ]] || [[ -z $MODULE_KICKSTARTER_UTILITIES_RACE ]] || [[ -z $MODULE_KICKSTARTER_UTILITIES_FACTION ]] || 
   [[ -z $MODULE_KICKSTARTER_UTILITIES_APPEARANCE ]] || [[ -z $MODULE_EXPERIENCED_ENABLED ]]; then
    echo -e "\e[0;33mAtleast one of the variables is missing or invalid\e[0m"
    exit 1
fi
